# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: rn-gauge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
        name: yarn install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
        name: yarn lint
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: typescript:typescheck
        name: yarn typescript:typescheck
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: prepare
        name: yarn prepare
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
        name: yarn test
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/
      - name: Build & Deploy
        working-directory: ./
        run: |
          yarn prepare
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
